export * from "./teacher";
export * from "./assistant";
export * from "./class";
export * from "./group";
export * from "./student";
export * from "./attendance";
export * from "./exam";
export * from "./payment";
export * from "./audit";
